### ISSUE TITLE
ADN getting hot and not working

### ISSUE THREAD

**Issue by lucacri** [kbjunky/ADNS9800#2]
Hey! I got the board that is veeeeery similar to this one (the one from Jack Enterprises - ADNS-9800 Laser Motion Sensor Breakout) and I assume they are basically the same pinouts/traces (correct me if i'm wrong of course!)

My problem is that i tried to use it in QMK with a RP2040. It worked really sporadically (like 3 times) when i had it on the breadboard and I jiggled the cables in the holes a bit. Once I saw that it worked by "jiggling", I thought that if I made the connections more permanent, it'd work all the time, but I was wrong.

After soldering (and re-do it twice again from scratch), the only thing that happens is that the ADN sensor gets hot to the touch (nothing crazy, not scalding but just pretty hot) and nothing works.

I'm at my wits end, do you have _any_ suggestion on how I could proceed?

**Comment by kbjunky** [comment]
I don't know how the board from Jack Enterprises is built thus can't help you much. My board is only compatible in size but pinout I don't know. Looking at the photos on Tindie seems like pinout is completely different. Try contacting Jack with your issue.
